spring:
  profiles:
    active: dev


---
server:
  port: 7081

spring:
  profiles: dev
  application:
    name: erp-config-7001

eureka:
  instance:
     #hostname: eureka7001.com
     hostname: 192.168.0.3
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



---
server:
  port: 7082
spring:
  profiles: test
  application:
    name: erp-config-7002
eureka:
  instance:
#    hostname: eureka7001.com
     hostname: 192.168.0.210
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

      
      
      
      
