spring:
  profiles:
    active: dev

---
server:
  port: 8001

spring:
   profiles: dev
   application:
    name: erp-config-provider-system
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.0.210:3306/erp_db_test              # 数据库名称
    username: root
    password: yg67120088c
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yg.erp.entities                 # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7081.com:7081/eureka
      defaultZone: http://192.168.0.46:7081/eureka

  instance:
    instance-id: erp-provider-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: ygtest-erp-system
  company.name: www.123.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8002

spring:
   profiles: test
   application:
    name: erp-config-provider-system
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.0.210:3306/erp_db_test             # 数据库名称
    username: root
    password: yg67120088c
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yg.erp.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7081.com:7081/eureka
      defaultZone: http://192.168.0.210:7082/eureka
  instance:
    instance-id: erp-provider-8002
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: ygtest-erp-system
  company.name: www.123.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

